repos:
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        alias: black-check
        args: [--config=pyproject.toml --check]
        stages: [push]
      - id: black
        alias: black-format
        args: [--config=pyproject.toml]
        stages: [commit]

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
      - id: isort
        alias: isort-check
        args: [--check-only --settings-file pyproject.toml]
        stages: [push]
      - id: isort
        alias: isort-format
        args: [--settings-file pyproject.toml]
        stages: [commit]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - Flake8-pyproject
        stages: [push]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        stages: [push]



